### ISSUE TITLE
COM pins configuration for 128x32 0.91" OLED display

### ISSUE THREAD

**Issue by mbradley612** [mongoose-os-libs/ssd1306#11]
If you are using a 128x32 0.91" OLED display, you have to set the com_pins configuration to be 0x02. With the default value of 0x12, the output on the display is compressed.
```
config_schema:
- ["ssd1306.com_pins", "i", 0x02, {title: "Screen COM pins configuration, depends on physical attachemnt of the panel to the chip; 0x02, 0x12, 0x22 or 0x32 are valid values"}]
```

Can you add a note to the README?

**Comment by rojer** [comment]
what is the brand of the display you are using?
com / offset settings can be different depending on particular implementation.
adding known names and configurations is a good idea.

**Comment by mbradley612** [comment]
It was sold as a MakerHawk I2C OLED Display Module I2C SSD1306 Screen Tiny Module 0.91 Inch White 128X32

Thanks

**Comment by rojer** [comment]
ok, so can you give full set of settings for it that you put in your config_schema?

**Comment by rojer** [comment]
```
  - ["ssd1306.width", 128]
  - ["ssd1306.height", 32]
  - ["ssd1306.com_pinx", 0x02]
```

like that?

**Comment by mbradley612** [comment]
Yes, like that!

**Comment by rojer** [comment]
added, thanks!
